name: Preview CI

on: [deployment_status]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Preview Environment
        env:
          STAGING_URL: ${{ github.event.deployment_status.target_url }}
        run: |
          echo STAGING_URL="$STAGING_URL"
          exit 1
