name: Preview CI

on: [deployment_status]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          STAGING_URL: ${{ github.event.deployment_status.target_url }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$STAGING_URL"
