name: Test Deployment

on: [deployment_status]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Test Deployed Environment
        env:
          STAGING_URL: ${{ github.event.deployment_status.target_url }}
          DEPLOYMENT_STATE: ${{ github.event.deployment_status.state }}
        run: |
          echo STAGING_URL="$STAGING_URL"
          echo DEPLOYMENT_STATE="$DEPLOYMENT_STATE"
          curl -f "$STAGING_URL"
